language: en

Symbol_before_Title: "【"
Symbol_after_Title: "】"

Titles:
  Beginner:
    name: "Beginner"
    permission: "none"
    color: yellow
  Admin:
    name: "Admin"
    permission: "PlayerTitlePrefix.admin"
    color: red
    isAdmin: true
